FROM gradle:8.5-jdk17-alpine AS builder

WORKDIR /app

COPY build.gradle.kts .
COPY src src

RUN gradle build -x test --no-daemon

FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 9090

CMD ["java", "-Xmx1024m", "-Xms256m", "-jar", "app.jar"]
